spring:
  config:
    import: optional:classpath:/sub/

  datasource:
    url: jdbc:mysql://localhost:3306/steady
    username: steady
    password: steady13

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    url: steady-api.json
